language: go

go:
  - 1.15.x

before_install:
  - go get -u github.com/mitchellh/gox
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.33.0

script:
  - make all

branches:
  only: 
    - /.*/

deploy:
  provider: releases
  file:
    - chirp_linux_amd64
    - chirp_darwin_amd64
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: AAdo/gxGZzxVpT/0XjQ8/YTodlOz7Jz+JRj8/HB5X7AIgnPgYFffhm31aXAPaRDWKF+z9Q5+AHCzz9ucYdeQhAhZ4YzWnfVI1FfcNu7cvDvLUhbWQjW1vJ/Vc7duGJyI7RKUukW0E9hxrGxu+I74TXsj7OVxlGxael0KXCdFydLrfjNF/lieAhHdN4NB707YQ4MPbZ7FnjVGnjhb/y7V/QH8At2APnK9gxoBmznDa5+VDm8i5TaCduFDM7FS5ypriJfaAo/wqmkTBEYe7bgumvMl1HEfVASVvyo9cY+9yVir82us/KkVT2uXU9ylIZCJgB8BmQc1ey9Y+EkxA/gQOhCaQAdQqkpvVrIAKE8N49+eTEn42cQ4xGx3HL2iK5r6nR0c+fOBGOtWlrb4w/ytu8XX701T4SwSx289th7JhZhQF1uY6ykzbnHKHqhv4HtTc6ztqYGBxSayuLwqFAnkCmip+IAmzKaQBDGo8rnfyv34BCd+6l3bupKAp5CMEu/LsM2OQCt58LfciAx6lto2085uDKbPWUhauGpsLkneaBnXXBYzjml69imGdbA3XFJ2eZ3T8WUVph5kDPn8g62GpbTlzcmzYlZM6PHgsZsUIHypSeOPIGNOt9expg0pgLP3MNySzuPRKNZedZiLfBb+CYcLgx49ZaousS8opc6yHW8=
